name: Auto Commit

on:
  schedule:
    # Runs every day at 6 AM UTC
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Make a dummy commit
      - name: Make a Dummy Commit
        run: |
          echo "Auto commit at $(date)" >> auto-green.log
          git config --global user.name "KhanPodMiu"
          git config --global user.email "KhanPodMiu@users.noreply.github.com"
          git add auto-green.log
          git commit -m "Auto commit to keep the green streak" || echo "No changes to commit"

      # Step 3: Authenticate and push changes
      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin main
