name: Auto Commit with Debugging

on:
  schedule:
    # Runs every day at 6 AM UTC
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Make a dummy commit
      - name: Make a Dummy Commit
        run: |
          echo "Auto commit at $(date)" >> auto-green.log
          git config --global user.name "KhanPodMiu"
          git config --global user.email "KhanPodMiu@users.noreply.github.com"
          git add auto-green.log
          git commit -m "Auto commit to keep the green streak" || echo "No changes to commit"

      # Debugging Git Configuration & Token
      - name: Debug Information
        run: |
          git status
          git remote -v
          echo "Actor: $GITHUB_ACTOR"
          echo "Repository: ${{ github.repository }}"
          echo "Token Available: ${{ secrets.GITHUB_TOKEN }}"

      # Set remote URL with token and attempt push
      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Setting remote with token..."
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push -u origin main
